title: Phase Space Echoes
description: A trip through physics and modeling.
theme: minima

markdown: kramdown

minima:
  skin: default

header_pages:
  - home.md
  - about.md
  - notes.md
  
kramdown:
  math_engine: mathjax
  input: GFM
